### ISSUE TITLE
Stanford: swap old source list with new list

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/beyond_the_paywall#22]
Stanford has provided an updated list of sources they would like added to their extension. See comment below for more details.

**Comment by betling** [comment]
no need for further legal clearance.  ted to meet/talk with engineering (rob?) to see what is needed to update lists.

**Comment by aaga** [comment]
I believe all that is required is for the Stanford team to submit a PR with the desired updates to [this file](https://github.com/mozilla-rally/beyond_the_paywall/blob/master/src/domains.js) which contains both lists. I can then approve the PR, create a new release, and publish a new version to the Add-on store.

**Comment by jepstein** [comment]
We are currently waiting for Stanford to provide the lists

**Comment by marniepw** [comment]
I have the updted file from Stanford. Note that the file they've provided uses a different file name than the domains.js that we're currently pointing at. GH won't let me attach the new file because it's a .js  Let me know when you're ready to update it, and we can figure something out.
