### ISSUE TITLE
Identify why Ad Module isn't sending data

### ISSUE THREAD

**Issue by knowtheory** [mozilla-rally/beyond_the_paywall#3]

**Comment by rhelmer** [comment]
OK I think I've identified the problem, the path to the content script that collects ads is incorrect:
https://github.com/mozilla-rally/beyond_the_paywall/blob/master/src/Advertisements.js#L42

It should be `"dist/content-scripts/page-ads.js"`

Unfortunately, dynamic content registration prints a rather cryptic error message, only to the browser console and only when the site is loaded:

`NS_ERROR_FILE_NOT_FOUND 2 ExtensionContent.jsm:172`

It would be nice if this was clearer, static content script registration (in `manifest.json`) at least prints:

`uncaught exception: Unable to load script: moz-extension://6f0ffaa0-bdb7-8f47-a74b-a10d0ca5771d/public/addon-build/content-script.js`

**Comment by rhelmer** [comment]
I generated a test ping, we're going to check tomorrow to see if it made it to the analysis environment.

**Comment by rhelmer** [comment]
Stanford folk verified that the test ping came in, and we shipped `0.1.6` to AMO.
