### ISSUE TITLE
Edits Needed

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/beyond_the_paywall#32]
@KimBMozilla @compzilla @knowtheory 
Content Edits Needed:
- [x] #33
- Rules have been reviewed by legal 
- Got rid of *most of the helping verbs. Still have a few "will's" in there for things that haven't happened/will continue to happen for weeks to come. Could use some help if this is a big thing. 
- Let me know if I need to go back over the steps under "how to" and how I can change them to make it more clear. 
- [ ] #34
- Edits on pg.1 only
- Please let me know if I'm missing any big concepts and if the overarching theme makes sense.
- [x] #35
- to go out Friday with an accompanying message. 
- [ ] #36
- Not on the look, just the overarching theme

Please provide edits [here](https://docs.google.com/document/d/1WgJqsYb6J0NMSSxrTuJclZ8JiHaG2I_Bm6cDLw9voBM/edit?usp=sharing).

**Comment by KimBMozilla** [comment]
clarifying: this list should be tackled in order, bottom up? Asking because you're outlining a newsroom-y workflow here (intentionally or not) and I interpret it as sequential.) I can do the stuff under the 90% edit

**Comment by compzilla** [comment]
I'll work on getting the Zilla Slab (primary) and Inter (secondary) fonts - unless you have those somewhere, Kennedy?

**Comment by compzilla** [comment]
Happy to help, but I'm not familiar with the % edits terminology - maybe message me what you mean.

**Comment by KennedyM-zillian** [comment]
Amy, I don't have those. Is that something we get from support? The % edit indicates how "done" I see them as. 
If possible, all edits by Friday would be amazing (Friday so I can send the Caption Contest flyer to Stanford and get it loaded into Tweetdeck and show Rebecca the infographics).

**Comment by KimBMozilla** [comment]
https://github.com/mozilla-rally/beyond_the_paywall/issues/33 is edited

**Comment by compzilla** [comment]
#34 is edited

**Comment by compzilla** [comment]
#35 is edited

**Comment by compzilla** [comment]
#36 Overarching theme is great.

**Comment by compzilla** [comment]
The infographics will be great to pin on Pinterest as well :)
