### ISSUE TITLE
90% Edit - Cartoon Caption Contest

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/beyond_the_paywall#33]

**Comment by KimBMozilla** [comment]
my physical redlining was too messy/tiny to scan/photo, so you're getting the full list of changes here:

**Comment by KimBMozilla** [comment]
- [ ] every PST needs to be PDT (Daylight Saving until Nov 6)
- [ ] under header Cartoon Caption Contest

**Comment by KimBMozilla** [comment]
- [ ] increase the font size for each description under the 4 graphics under  "How It Works"
